/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package QuizPortal;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;
import java.io.Serializable;
import javax.swing.JOptionPane;

/**
 *
 * @author Manvendra-Harshit
 */
public class ADMIN extends javax.swing.JFrame {

    /**
     * Creates new form STUDENT
     */
    static Socket socket;
    public ADMIN() {
        initComponents();
        try{
            socket = new Socket("localhost", 5436);
        }catch(IOException e){
            JOptionPane.showMessageDialog(null,"Server Offline");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        signup = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        rpassword = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        username = new javax.swing.JTextField();
        login = new javax.swing.JLabel();
        rname = new javax.swing.JTextField();
        rusername = new javax.swing.JTextField();
        rsecuritycode = new javax.swing.JTextField();
        BACK = new javax.swing.JLabel();
        CLOSE = new javax.swing.JLabel();
        MINIMIZE = new javax.swing.JLabel();
        xyz = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        signup.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signupMouseClicked(evt);
            }
        });
        getContentPane().add(signup, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 530, 130, 40));

        jLabel5.setForeground(new java.awt.Color(204, 204, 255));
        jLabel5.setText("SECURITY CODE");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 420, 120, -1));

        jLabel4.setForeground(new java.awt.Color(204, 204, 255));
        jLabel4.setText("NAME");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("PASSWORD");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, -1, -1));

        jLabel1.setForeground(new java.awt.Color(230, 230, 230));
        jLabel1.setText("USERNAME");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, -1, -1));

        rpassword.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rpassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        rpassword.setBorder(null);
        rpassword.setOpaque(false);
        getContentPane().add(rpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 350, 50));

        password.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        password.setBorder(null);
        password.setOpaque(false);
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 445, 280, 60));

        username.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        username.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        username.setBorder(null);
        username.setOpaque(false);
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        getContentPane().add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 360, 280, 60));

        login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginMouseClicked(evt);
            }
        });
        getContentPane().add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 536, 110, 40));

        rname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        rname.setBorder(null);
        rname.setOpaque(false);
        rname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rnameActionPerformed(evt);
            }
        });
        getContentPane().add(rname, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 350, 60));

        rusername.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rusername.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        rusername.setBorder(null);
        rusername.setOpaque(false);
        getContentPane().add(rusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 350, 50));

        rsecuritycode.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rsecuritycode.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        rsecuritycode.setBorder(null);
        rsecuritycode.setOpaque(false);
        getContentPane().add(rsecuritycode, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, 350, 50));

        BACK.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BACK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BACKMouseClicked(evt);
            }
        });
        getContentPane().add(BACK, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 0, 40, 40));

        CLOSE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CLOSE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CLOSEMouseClicked(evt);
            }
        });
        getContentPane().add(CLOSE, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 0, 40, 40));

        MINIMIZE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MINIMIZE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MINIMIZEMouseClicked(evt);
            }
        });
        getContentPane().add(MINIMIZE, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 0, 40, 40));

        xyz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QuizPortal/admin1.jpg"))); // NOI18N
        xyz.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                xyzMouseClicked(evt);
            }
        });
        getContentPane().add(xyz, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 600));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 350, 50));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void BACKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BACKMouseClicked
        new HOME().setVisible(true);
        dispose();
    }//GEN-LAST:event_BACKMouseClicked

    private void CLOSEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CLOSEMouseClicked
        System.exit(0);
    }//GEN-LAST:event_CLOSEMouseClicked

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    private void signupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signupMouseClicked
       if(!rsecuritycode.getText().equals("QuizPortal"))
       {
           JOptionPane.showMessageDialog(null,"Wrong Security Code");
       }
       else 
       { 
           try{
               sendMessage(socket,"signupt",rusername.getText(),rpassword.getText(),rname.getText());
           }catch(IOException e){
               e.printStackTrace();
           }
               
       }
    }//GEN-LAST:event_signupMouseClicked

    private void rnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rnameActionPerformed

    private void xyzMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xyzMouseClicked
           
            
    }//GEN-LAST:event_xyzMouseClicked

    private void MINIMIZEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MINIMIZEMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_MINIMIZEMouseClicked

    private void loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseClicked
        // TODO add your handling code here:
         char[] p = password.getPassword();
            String password1 = new String(p);
            String response;
            ObjectInputStream objectInputStream;
            try{
                sendMessage(socket,"logint", username.getText(), password1);
                objectInputStream = new ObjectInputStream(socket.getInputStream());
                response = (String) objectInputStream.readObject();
                if(response.equals("verified"))
                {new Subject(socket).setVisible(true);
                dispose();
                }
                else
                JOptionPane.showMessageDialog(null,"Wrong Creditials");
            }catch(IOException|ClassNotFoundException e){
                e.printStackTrace();
            }
            username.setText("");
            password.setText("");
    }//GEN-LAST:event_loginMouseClicked
public void sendMessage
            (Socket socket, String type, String username,String password,String name)
            throws IOException {
        ObjectOutputStream objectOutputStream =
                new ObjectOutputStream(socket.getOutputStream());
        //while (true) {
          //  System.out.println("Press 1 to quit");
            //int ch = Integer.parseInt(bufferedReader.readLine());
            //if (ch == 1) {
              //  break;
            //}

            //System.out.println("Enter message");
            //String text = bufferedReader.readLine();
            String[] message={type,username,password,name};
            
            //String from = "Client - " + name;
           // Message message = new Message(text, from, "Server");
          
            objectOutputStream.writeObject(message);
            objectOutputStream.flush();
        //}
            }
    public void sendMessage
            (Socket socket, String type, String username,String password)
            throws IOException {
        ObjectOutputStream objectOutputStream =
                new ObjectOutputStream(socket.getOutputStream());
        //while (true) {
          //  System.out.println("Press 1 to quit");
            //int ch = Integer.parseInt(bufferedReader.readLine());
            //if (ch == 1) {
              //  break;
            //}

            //System.out.println("Enter message");
            //String text = bufferedReader.readLine();
            String[] message={type,username,password};
            
            //String from = "Client - " + name;
           // Message message = new Message(text, from, "Server");
          
            objectOutputStream.writeObject(message);
            objectOutputStream.flush();
        //}
            }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ADMIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ADMIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ADMIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ADMIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ADMIN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BACK;
    private javax.swing.JLabel CLOSE;
    private javax.swing.JLabel MINIMIZE;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel login;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField rname;
    private javax.swing.JTextField rpassword;
    private javax.swing.JTextField rsecuritycode;
    private javax.swing.JTextField rusername;
    private javax.swing.JLabel signup;
    private javax.swing.JTextField username;
    private javax.swing.JLabel xyz;
    // End of variables declaration//GEN-END:variables
}

    

    








