/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package QuizPortal;
import static QuizPortal.sectionStudent.socket;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;
import javax.swing.JOptionPane;

/**
 *
 * @author Manvendra
 * 
 *
 */
class timeThread implements Runnable{
    //private static Thread t;
    private static AnswersStudent Rk;
    private static int TotalMinutes;
    private static int TotalSeconds;
    private static Thread t;
    public timeThread(int time, AnswersStudent Rk){
        this.Rk = Rk;
        TotalMinutes = time/60;
        TotalSeconds = time%60;
        t = new Thread(this);
    }
    @Override public void run(){
        int Minute=TotalMinutes;
        int Second=TotalSeconds;
        System.out.println("Minute "+Minute);
        while(true){
                try{
                     Rk.setTime(Minute, Second);
                     t.sleep(1000);
                     System.out.println(Minute+" "+Second);
                     Second--;
                     System.out.println(Minute+" "+Second);
                     if(Second==-1){
                         Minute--;
                         Second=59;
                                 
                     }
                }catch(Exception e){
                    e.printStackTrace();
                }
            }      
        }
    public void start(){
        t.start();
    }
    public void stop(){
        t.stop();
    }
    public void suspend(){
        t.suspend();
    }
    public void resume(){
        t.resume();
    }
}

public class AnswersStudent extends javax.swing.JFrame {
    
    /**
     * Creates new form AnswersStudent
     */
    
    private static Socket socket;
    private static String username;
    private static String qcode;
    private static int mcqsscore;
    private static int currentmcqs;
    private static int totalquestionsmcqs;
    private static String[][] questionmcqs;  
    public  timeThread tt;
    private static Thread t;
    private static int totaltime;
    static int count;
    //static ButtonGroup bg;
    public AnswersStudent(Socket socket,String username,String qcode,int currentmcqs,int mcqsscore,int totaltime, int totalquestionsmcqs,String questionmcqs[][]){
        initComponents();
        this.socket = socket;
        this.qcode = qcode;
        this.username=username;
        this.mcqsscore=mcqsscore;
        
        
        this.totalquestionsmcqs=totalquestionsmcqs;
        this.currentmcqs=currentmcqs;
        this.questionmcqs=questionmcqs;
        
        this.totaltime = totaltime;
        this.tt = new timeThread(totaltime, this);
        question.setText(questionmcqs[currentmcqs][0]);
        opt1.setText(questionmcqs[currentmcqs][1]);
        opt2.setText(questionmcqs[currentmcqs][2]);
        opt3.setText(questionmcqs[currentmcqs][3]);
        opt4.setText(questionmcqs[currentmcqs][4]);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        endsection = new javax.swing.JLabel();
        question = new javax.swing.JTextField();
        opt1 = new javax.swing.JRadioButton();
        opt2 = new javax.swing.JRadioButton();
        opt3 = new javax.swing.JRadioButton();
        opt4 = new javax.swing.JRadioButton();
        time = new javax.swing.JTextField();
        submit = new javax.swing.JLabel();
        switchsec = new javax.swing.JLabel();
        cross = new javax.swing.JLabel();
        minimize = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 600));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        endsection.setBackground(new java.awt.Color(255, 0, 51));
        endsection.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        endsection.setForeground(new java.awt.Color(102, 255, 255));
        endsection.setText("END SECTION");
        endsection.setOpaque(true);
        endsection.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                endsectionMouseClicked(evt);
            }
        });
        getContentPane().add(endsection, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 540, 200, 40));
        getContentPane().add(question, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 790, 120));

        opt1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        opt1.setOpaque(false);
        opt1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                opt1MouseClicked(evt);
            }
        });
        getContentPane().add(opt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 860, 50));

        opt2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        opt2.setOpaque(false);
        opt2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                opt2MouseClicked(evt);
            }
        });
        getContentPane().add(opt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 840, 40));

        opt3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        opt3.setOpaque(false);
        opt3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                opt3MouseClicked(evt);
            }
        });
        getContentPane().add(opt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, 840, 50));

        opt4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        opt4.setOpaque(false);
        opt4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                opt4MouseClicked(evt);
            }
        });
        getContentPane().add(opt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 490, 830, 50));

        time.setFont(new java.awt.Font("DS-Digital", 1, 36)); // NOI18N
        time.setForeground(new java.awt.Color(0, 0, 225));
        getContentPane().add(time, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 140, 90, 70));

        submit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitMouseClicked(evt);
            }
        });
        getContentPane().add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(681, 550, 170, 50));

        switchsec.setBackground(new java.awt.Color(0, 0, 255));
        switchsec.setForeground(new java.awt.Color(255, 255, 255));
        switchsec.setText("  Switch Sec");
        switchsec.setOpaque(true);
        switchsec.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                switchsecMouseClicked(evt);
            }
        });
        getContentPane().add(switchsec, new org.netbeans.lib.awtextra.AbsoluteConstraints(901, 510, 90, 90));

        cross.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                crossMouseClicked(evt);
            }
        });
        getContentPane().add(cross, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 10, 30, 30));
        getContentPane().add(minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 10, 40, 30));

        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 0, 40, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QuizPortal/questions.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 600));

        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 480, 90, 110));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public void setTime(int Minutes, int Seconds){
        if(Minutes != -1)
            time.setText(Minutes + ":" + Seconds);
        else
        {
            try{
            ObjectOutputStream objectOutputStream =new ObjectOutputStream(socket.getOutputStream());
            String[] s = {"sectioncompletemcqs",qcode,username,mcqsscore+"","0"};
            objectOutputStream.writeObject(s);
            sectionStudent.flags = 1;
            sectionStudent.s1.setVisible(false);
            dispose();
            }
            catch(IOException e){
            e.printStackTrace();
            }
            JOptionPane.showMessageDialog(null, "Time-Over!");
            count = -1;
            tt.stop();
        }
    }
    private void submitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitMouseClicked
           String userans="E";
           if(opt1.isSelected())
               userans="A";
           else if(opt2.isSelected())
               userans="B";
           else if(opt3.isSelected())
               userans="C";
           else if(opt4.isSelected())
               userans="D";
           if(userans.equals(questionmcqs[currentmcqs][5])){
                mcqsscore++;
           }
           System.out.println(questionmcqs[currentmcqs][5]); 
           currentmcqs++;
          
           if(currentmcqs != totalquestionsmcqs)
           {
             //  System.out.println("Q.no. "+currentmcqs+" completed");
               opt1.setSelected(false);
               opt2.setSelected(false);
               opt3.setSelected(false);
               opt4.setSelected(false);
               question.setText(questionmcqs[currentmcqs][0]);
               opt1.setText(questionmcqs[currentmcqs][1]);
               opt2.setText(questionmcqs[currentmcqs][2]);
               opt3.setText(questionmcqs[currentmcqs][3]);
               opt4.setText(questionmcqs[currentmcqs][4]); 
           }
           else
           {
               question.setText("SECTION OVER!");
               opt1.setText("N/A");
               opt2.setText("N/A");
               opt3.setText("N/A");
               opt4.setText("N/A");
               JOptionPane.showMessageDialog(null,"Section is over, Click on END SECTION!");   
           }             
             
    }//GEN-LAST:event_submitMouseClicked

    private void crossMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crossMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_crossMouseClicked

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked

        new SelectStudent(socket,username).setVisible(true);
        dispose();
    }//GEN-LAST:event_backMouseClicked

    private void opt1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_opt1MouseClicked
       opt1.setSelected(true);
       opt2.setSelected(false);
       opt3.setSelected(false);
       opt4.setSelected(false);
       
    }//GEN-LAST:event_opt1MouseClicked

    private void opt2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_opt2MouseClicked
        // TODO add your handling code here:
       opt1.setSelected(false);
       opt2.setSelected(true);
       opt3.setSelected(false);
       opt4.setSelected(false);
    }//GEN-LAST:event_opt2MouseClicked

    private void opt3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_opt3MouseClicked
        // TODO add your handling code here:
       opt1.setSelected(false);
       opt2.setSelected(false);
       opt3.setSelected(true);
       opt4.setSelected(false);
    }//GEN-LAST:event_opt3MouseClicked

    private void opt4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_opt4MouseClicked
       opt1.setSelected(false);
       opt2.setSelected(false);
       opt3.setSelected(false);
       opt4.setSelected(true);
    }//GEN-LAST:event_opt4MouseClicked

    private void switchsecMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_switchsecMouseClicked
        // TODO add your handling code here:
        
        //tt.stop();
        //new Rating(socket,username,score,quizcode).setVisible(true);
        tt.suspend();
        this.setVisible(false);
      //  AnswerMultiple(socket,username,qcode,currentmcqm,mcqmscore,totalquestionsmcqm,questionmcqm).setVisible(true);
    }//GEN-LAST:event_switchsecMouseClicked

    private void endsectionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_endsectionMouseClicked
         try{
            ObjectOutputStream objectOutputStream =new ObjectOutputStream(socket.getOutputStream());
            String[] s = {"sectioncompletemcqs",qcode,username,mcqsscore+"","0"};
            objectOutputStream.writeObject(s);
        }catch(IOException e){
            e.printStackTrace();
        }
         JOptionPane.showMessageDialog(null,"Responses Saved");
         sectionStudent.flags = 1;
         tt.stop();
         dispose();
        
    }//GEN-LAST:event_endsectionMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnswersStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnswersStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnswersStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnswersStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnswersStudent(socket,username,qcode,currentmcqs,mcqsscore,totaltime, totalquestionsmcqs,questionmcqs).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JLabel cross;
    private javax.swing.JLabel endsection;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel minimize;
    private javax.swing.JRadioButton opt1;
    private javax.swing.JRadioButton opt2;
    private javax.swing.JRadioButton opt3;
    private javax.swing.JRadioButton opt4;
    private javax.swing.JTextField question;
    private javax.swing.JLabel submit;
    private javax.swing.JLabel switchsec;
    private javax.swing.JTextField time;
    // End of variables declaration//GEN-END:variables
}
