/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package QuizPortal;

import static QuizPortal.AnswersStudent.count;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.net.Socket;
import javax.swing.JOptionPane;

/**
 *
 * @author Manvendra-Harshit
 */

class timeThreadm implements Runnable{
    //private static Thread t;
    private static AnswerMultiple Nk;
    private static int TotalMinutes;
    private static int TotalSeconds;
    private static Thread t;
    public timeThreadm(int time, AnswerMultiple Nk){
        this.Nk = Nk;
        TotalMinutes = time/60;
        TotalSeconds = time%60;
        t = new Thread(this);
    }
    @Override public void run(){
        int Minute=TotalMinutes;
        int Second=TotalSeconds;
        while(true){
                try{
                     Nk.setTimem(Minute, Second);
                     t.sleep(1000);
                     System.out.println(Minute+" "+Second);
                     Second--;
                     System.out.println(Minute+" "+Second);
                     if(Second==-1){
                         Minute--;
                         Second=59;
                                 
                     }
                }catch(Exception e){
                    e.printStackTrace();
                }
            }      
        }
    public void start(){
        t.start();
    }
    public void stop(){
        t.stop();
    }
    public void suspend(){
        t.suspend();
    }
    public void resume(){
        t.resume();
    }
}



public class AnswerMultiple extends javax.swing.JFrame {

    /**
     * Creates new form AnswerMultiple
     */
    
    private static Socket socket;
    private static String username;
    private static String qcode;
    private static int mcqmscore;
    private static int currentmcqm;
    private static int totalquestionsmcqm;
    private static int totaltime;
    public timeThreadm ttm;
    static int count;
    private static String[][] questionmcqm;
    public AnswerMultiple(Socket socket,String username,String qcode,int currentmcqm,int mcqmscore,int totaltime, int totalquestionsmcqm,String questionmcqm[][]) {
        initComponents();
        this.socket = socket;
        this.qcode = qcode;
        this.username=username;
        this.mcqmscore=mcqmscore;
        this.currentmcqm=currentmcqm;
        this.totalquestionsmcqm=totalquestionsmcqm;
        this.questionmcqm=questionmcqm;
        //currentmcqm=(int)((Math.random()*((totalquestionsmcqm-0-1)+1))+0);
        //this.totaltime = Integer.parseInt(questionmcqm[0][5]);
        this.totaltime = totaltime;
        ttm = new timeThreadm(totaltime, this);
        question.setText(questionmcqm[currentmcqm][0]);
        opt1.setText(questionmcqm[currentmcqm][1]);
        opt2.setText(questionmcqm[currentmcqm][2]);
        opt3.setText(questionmcqm[currentmcqm][3]);
        opt4.setText(questionmcqm[currentmcqm][4]);
        //currentmcqm=(currentmcqm++)%totalquestionsmcqm;
        //count=totalquestionsmcqm;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        question = new javax.swing.JTextArea();
        endsection = new javax.swing.JLabel();
        opt4 = new javax.swing.JRadioButton();
        opt1 = new javax.swing.JRadioButton();
        opt2 = new javax.swing.JRadioButton();
        opt3 = new javax.swing.JRadioButton();
        submit = new javax.swing.JLabel();
        switchsec = new javax.swing.JLabel();
        time = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        question.setColumns(20);
        question.setRows(5);
        jScrollPane1.setViewportView(question);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 790, 120));

        endsection.setBackground(new java.awt.Color(0, 153, 0));
        endsection.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        endsection.setForeground(new java.awt.Color(255, 255, 255));
        endsection.setText("     END SECTION");
        endsection.setOpaque(true);
        endsection.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                endsectionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                endsectionMouseEntered(evt);
            }
        });
        getContentPane().add(endsection, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 550, 210, 40));

        opt4.setOpaque(false);
        getContentPane().add(opt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 490, 830, 50));

        opt1.setOpaque(false);
        opt1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                opt1MouseClicked(evt);
            }
        });
        getContentPane().add(opt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 235, 830, 50));

        opt2.setOpaque(false);
        opt2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                opt2MouseClicked(evt);
            }
        });
        getContentPane().add(opt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 830, 50));

        opt3.setOpaque(false);
        opt3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                opt3MouseClicked(evt);
            }
        });
        getContentPane().add(opt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 830, 50));

        submit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitMouseClicked(evt);
            }
        });
        getContentPane().add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 546, 170, 50));

        switchsec.setBackground(new java.awt.Color(51, 51, 255));
        switchsec.setForeground(new java.awt.Color(255, 255, 255));
        switchsec.setText("SWITCH SEC");
        switchsec.setOpaque(true);
        switchsec.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                switchsecMouseClicked(evt);
            }
        });
        getContentPane().add(switchsec, new org.netbeans.lib.awtextra.AbsoluteConstraints(901, 506, 90, 90));

        time.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        time.setForeground(new java.awt.Color(0, 0, 204));
        time.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        time.setText("jTextField1");
        time.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        getContentPane().add(time, new org.netbeans.lib.awtextra.AbsoluteConstraints(899, 142, 90, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QuizPortal/questions.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    public void setTimem(int Minutes, int Seconds){
        if(Minutes!=-1)
            time.setText(Minutes + ":" + Seconds);
        else{
            try{
            ObjectOutputStream objectOutputStream =new ObjectOutputStream(socket.getOutputStream());
            String[] s = {"sectioncompletemcqm",qcode,username,mcqmscore+"","0"};
            objectOutputStream.writeObject(s);
            sectionStudent.flagm = 1;
            sectionStudent.m1.setVisible(false);
            dispose();
            }catch(IOException e){
            e.printStackTrace();
            }
            JOptionPane.showMessageDialog(null, "Time-Over!");
            count = -1;
            ttm.stop();
        }
        
    }
    private void submitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitMouseClicked
        // TODO add your handling code here:
        String userans="";
           if(opt1.isSelected())
               userans+="A";
           if(opt2.isSelected())
               userans+="B";
           if(opt3.isSelected())
               userans+="C";
           if(opt4.isSelected())
               userans+="D";
           if(userans.equals(questionmcqm[currentmcqm][5])){
                mcqmscore++;
           }        
           currentmcqm++;
           if(currentmcqm!=totalquestionsmcqm)
           {
               question.setText(questionmcqm[currentmcqm][0]);
               opt1.setText(questionmcqm[currentmcqm][1]);
               opt2.setText(questionmcqm[currentmcqm][2]);
               opt3.setText(questionmcqm[currentmcqm][3]);
               opt4.setText(questionmcqm[currentmcqm][4]);
               opt1.setSelected(false);
               opt2.setSelected(false);
               opt3.setSelected(false);
               opt4.setSelected(false);        
           }
           else
           {
               question.setText("SECTION OVER!");
               opt1.setText("N/A");
               opt2.setText("N/A");
               opt3.setText("N/A");
               opt4.setText("N/A");
               //tt.stop();
               JOptionPane.showMessageDialog(null,"Section is over, click on END SECTION!");
               
           }             
    }//GEN-LAST:event_submitMouseClicked

    private void opt1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_opt1MouseClicked
        // TODO add your handling code here:
       /*  opt1.setSelected(true);
       opt2.setSelected(false);
       opt3.setSelected(false);
       opt4.setSelected(false);
        */
       
    }//GEN-LAST:event_opt1MouseClicked

    private void opt2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_opt2MouseClicked
        // TODO add your handling code here:
       /* opt1.setSelected(false);
       opt2.setSelected(true);
       opt3.setSelected(false);
       opt4.setSelected(false);
        */
    }//GEN-LAST:event_opt2MouseClicked

    private void opt3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_opt3MouseClicked
        // TODO add your handling code here:
        /* opt1.setSelected(false);
       opt2.setSelected(false);
       opt3.setSelected(true);
       opt4.setSelected(false);
        */
    }//GEN-LAST:event_opt3MouseClicked

    private void switchsecMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_switchsecMouseClicked
        // TODO add your handling code here:
         ttm.suspend();
         this.setVisible(false);
    }//GEN-LAST:event_switchsecMouseClicked

    private void endsectionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_endsectionMouseClicked
        // TODO add your handling code here:
         try{
            ObjectOutputStream objectOutputStream =new ObjectOutputStream(socket.getOutputStream());
            String[] s = {"sectioncompletemcqm",qcode,username,mcqmscore+"","0"};
            objectOutputStream.writeObject(s);
        }catch(IOException e){
            e.printStackTrace();
        }
         JOptionPane.showMessageDialog(null,"Responses Saved!");
         sectionStudent.flagm = 1;
         ttm.stop();
         dispose();
    }//GEN-LAST:event_endsectionMouseClicked

    private void endsectionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_endsectionMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_endsectionMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnswerMultiple.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnswerMultiple.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnswerMultiple.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnswerMultiple.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                    new AnswerMultiple(socket,username,qcode,currentmcqm,mcqmscore, totaltime, totalquestionsmcqm,questionmcqm).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel endsection;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton opt1;
    private javax.swing.JRadioButton opt2;
    private javax.swing.JRadioButton opt3;
    private javax.swing.JRadioButton opt4;
    private javax.swing.JTextArea question;
    private javax.swing.JLabel submit;
    private javax.swing.JLabel switchsec;
    private javax.swing.JTextField time;
    // End of variables declaration//GEN-END:variables
}
