/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package QuizPortal;

import static QuizPortal.AnswerMultiple.count;
import static QuizPortal.AnswersStudent.count;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.net.Socket;
import javax.swing.JOptionPane;

/**
 *
 * @author Manvendra-harshit
 */

class timeThreadt implements Runnable{
    //private static Thread t;
    private static AnswerTrue Sk;
    private static int TotalMinutes;
    private static int TotalSeconds;
    private static Thread t;
    public timeThreadt(int time, AnswerTrue Sk){
        this.Sk = Sk;
        TotalMinutes = time/60;
        TotalSeconds = time%60;
        t = new Thread(this);
    }
    @Override public void run(){
        int Minute=TotalMinutes;
        int Second=TotalSeconds;
        while(true){
                try{
                     Sk.setTimetf(Minute, Second);
                     t.sleep(1000);
                     System.out.println(Minute+" "+Second);
                     Second--;
                     System.out.println(Minute+" "+Second);
                     if(Second==-1){
                         Minute--;
                         Second=59;
                                 
                     }
                }catch(Exception e){
                    e.printStackTrace();
                }
            }      
        }
    public void start(){
        t.start();
    }
    public void stop(){
        t.stop();
    }
    public void suspend(){
        t.suspend();
    }
    public void resume(){
        t.resume();
    }
}

public class AnswerTrue extends javax.swing.JFrame {

    /**
     * Creates new form AnswerTrue
     */
        
    private static Socket socket;
    private static String username;
    private static String qcode;
    private static int tfscore;
    private static int currenttf;
    private static int totaltime;
    public timeThreadt ttt;
    static int count;
    private static int totalquestionstf;
    private static String[][] questiontf; 
    public AnswerTrue(Socket socket,String username,String qcode,int currenttf,int tfscore,int totaltime, int totalquestionstf,String questiontf[][]) {
        initComponents();
        this.socket = socket;
        this.qcode = qcode;
        this.username=username;
        this.tfscore=tfscore;
        this.currenttf=currenttf;
        this.totalquestionstf=totalquestionstf;
        
        this.totaltime = totaltime;
       // System.out.println("Total Time "+totaltime);
        this.ttt = new timeThreadt(totaltime, this);
        
        this.questiontf=questiontf; 
        question.setText(questiontf[currenttf][0]);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        question = new javax.swing.JTextArea();
        tf = new javax.swing.JTextField();
        submit = new javax.swing.JLabel();
        endsec = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cross = new javax.swing.JLabel();
        switchsec = new javax.swing.JLabel();
        time = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        question.setColumns(20);
        question.setRows(5);
        jScrollPane1.setViewportView(question);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 810, 110));
        getContentPane().add(tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 110, 50));

        submit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitMouseClicked(evt);
            }
        });
        getContentPane().add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 490, 190, 50));

        endsec.setBackground(new java.awt.Color(255, 0, 51));
        endsec.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        endsec.setForeground(new java.awt.Color(255, 255, 255));
        endsec.setText("END SECTION");
        endsec.setOpaque(true);
        endsec.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                endsecMouseClicked(evt);
            }
        });
        getContentPane().add(endsec, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 420, 170, 150));
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 6, 40, 30));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 6, 50, 40));
        getContentPane().add(cross, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 6, 50, 40));

        switchsec.setBackground(new java.awt.Color(0, 0, 255));
        switchsec.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        switchsec.setForeground(new java.awt.Color(255, 255, 255));
        switchsec.setText("SWITCH SEC");
        switchsec.setOpaque(true);
        switchsec.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                switchsecMouseClicked(evt);
            }
        });
        getContentPane().add(switchsec, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 426, 120, 130));

        time.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        time.setForeground(new java.awt.Color(0, 51, 153));
        time.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        time.setText("skjdfh");
        time.setBorder(null);
        time.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        getContentPane().add(time, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, 80, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QuizPortal/tf.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void setTimetf(int Minutes, int Seconds){
        if(Minutes!=-1)
            time.setText(Minutes + ":" + Seconds);
        else{
            try{
            ObjectOutputStream objectOutputStream =new ObjectOutputStream(socket.getOutputStream());
            String[] s = {"sectioncompletetf",qcode,username,tfscore+"","0"};
            objectOutputStream.writeObject(s);
            sectionStudent.flagt = 1;
            sectionStudent.t1.setVisible(false);
            dispose();
            }catch(IOException e){
            e.printStackTrace();
            }
            JOptionPane.showMessageDialog(null, "Time-Over!");
            count = -1;
            ttt.stop();
        }
    }
    private void submitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitMouseClicked
        // TODO add your handling code here:
        String userans="";
        String s1 = tf.getText();
        if(s1.equals("T"))
            userans="T";
        else if(s1.equals("F"))
            userans="F";
         if(userans.equals(questiontf[currenttf][1])){
                tfscore++;
         }
         //System.out.println(questiontf[currenttf][1]);
          currenttf++;
           if(currenttf!=totalquestionstf)
           {
               question.setText(questiontf[currenttf][0]);
               tf.setText("N/A");    
           }
           else
           {
               JOptionPane.showMessageDialog(null,"Section is over, Click on END SECTION!");
               
           }             
             
    }//GEN-LAST:event_submitMouseClicked
    
    
    private void switchsecMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_switchsecMouseClicked
        
        ttt.suspend();
        this.setVisible(false);
    }//GEN-LAST:event_switchsecMouseClicked

    private void endsecMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_endsecMouseClicked
        // TODO add your handling code here:
         try{
            ObjectOutputStream objectOutputStream =new ObjectOutputStream(socket.getOutputStream());
            String[] s = {"sectioncompletetf",qcode,username,tfscore+"","0"};
            objectOutputStream.writeObject(s);
        }catch(IOException e){
            e.printStackTrace();
        }
         JOptionPane.showMessageDialog(null,"Responses Saved");
         sectionStudent.flagt = 1;
         ttt.stop();
         dispose();
        
    }//GEN-LAST:event_endsecMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnswerTrue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnswerTrue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnswerTrue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnswerTrue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnswerTrue(socket,username,qcode,currenttf,tfscore,totaltime, totalquestionstf,questiontf).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JLabel cross;
    private javax.swing.JLabel endsec;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea question;
    private javax.swing.JLabel submit;
    private javax.swing.JLabel switchsec;
    private javax.swing.JTextField tf;
    private javax.swing.JTextField time;
    // End of variables declaration//GEN-END:variables
}
