/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package QuizPortal;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;
import javax.swing.JOptionPane;

/**
 *
 * @author Manvendra
 */
public class Rating extends javax.swing.JFrame {
   
    
    static Socket socket;
    static int score;
    static int finalscore;
    static String username;
    static float rating;
    static String qcode;
    
    /**
     * Creates new form Rating
     */
    public Rating(Socket socket,String username,String qcode) {
        initComponents();
        this.socket=socket;
        this.username=username;
        this.score=score;
        this.qcode=qcode;
        
        
        
        
        try{
            ObjectOutputStream objectOutputStream =new ObjectOutputStream(socket.getOutputStream());
            String[] s = {"rating",qcode};
            objectOutputStream.writeObject(s);
        }catch(IOException e){
            e.printStackTrace();
        }
        try{
            ObjectInputStream objectInputStream = new ObjectInputStream(socket.getInputStream());
            String[] str = (String[]) objectInputStream.readObject( );
            rat.setText(str[0]);
        }catch(IOException|ClassNotFoundException e){
            e.printStackTrace();
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rat = new javax.swing.JTextField();
        r3 = new javax.swing.JRadioButton();
        r1 = new javax.swing.JRadioButton();
        r4 = new javax.swing.JRadioButton();
        send = new javax.swing.JLabel();
        r2 = new javax.swing.JRadioButton();
        r5 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(rat, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 170, 70, 50));

        r3.setOpaque(false);
        r3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                r3MouseClicked(evt);
            }
        });
        getContentPane().add(r3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 400, 40, 30));

        r1.setOpaque(false);
        r1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                r1MouseClicked(evt);
            }
        });
        getContentPane().add(r1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 405, -1, -1));

        r4.setContentAreaFilled(false);
        r4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                r4MouseClicked(evt);
            }
        });
        getContentPane().add(r4, new org.netbeans.lib.awtextra.AbsoluteConstraints(515, 400, 40, 30));

        send.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QuizPortal/send.jpg"))); // NOI18N
        send.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        send.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sendMouseClicked(evt);
            }
        });
        getContentPane().add(send, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 390, 130, 140));

        r2.setOpaque(false);
        r2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                r2MouseClicked(evt);
            }
        });
        getContentPane().add(r2, new org.netbeans.lib.awtextra.AbsoluteConstraints(425, 400, 40, 30));

        r5.setOpaque(false);
        r5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                r5MouseClicked(evt);
            }
        });
        getContentPane().add(r5, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 400, 40, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QuizPortal/rating.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sendMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sendMouseClicked
        String  rating1 = "0";
         if(r5.isSelected())
               rating1="5";
           else if(r4.isSelected())
               rating1="4";
           else if(r3.isSelected())
               rating1="3";
           else if(r2.isSelected())
               rating1="2";
           else if(r1.isSelected())
               rating1="1";
         System.out.println(rating1);
        try{
                    ObjectOutputStream objectOutputStream =new ObjectOutputStream(socket.getOutputStream());
                    String[] s = {"final",qcode,username,rating1};
                    objectOutputStream.writeObject(s);
                }catch(IOException e){
                    e.printStackTrace();
                }  
         try{
            ObjectInputStream objectInputStream = new ObjectInputStream(socket.getInputStream());
            this.finalscore = (int) objectInputStream.readObject( );
            //rat.setText(str[0]);
            
        }catch(IOException|ClassNotFoundException e){
            e.printStackTrace();
        }
        JOptionPane.showMessageDialog(null,"Score - "+finalscore);
        new HOME().setVisible(true);
        dispose();
    }//GEN-LAST:event_sendMouseClicked

    private void r5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_r5MouseClicked
       r1.setSelected(true);
       r2.setSelected(true);
       r5.setSelected(true);
       r3.setSelected(true);
       r4.setSelected(true);
    }//GEN-LAST:event_r5MouseClicked

    private void r4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_r4MouseClicked
       r1.setSelected(true);
       r2.setSelected(true);
       r3.setSelected(true);
       r4.setSelected(true);
       r5.setSelected(false);
    }//GEN-LAST:event_r4MouseClicked

    private void r3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_r3MouseClicked
        // TODO add your handling code here:  r1.setSelected(true);
        r1.setSelected(true);
        r2.setSelected(true);
        r3.setSelected(true);
        r4.setSelected(false);
        r5.setSelected(false);
    }//GEN-LAST:event_r3MouseClicked

    private void r2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_r2MouseClicked
        // TODO add your handling code here:
       r1.setSelected(true);
       r3.setSelected(false);
       r4.setSelected(false);
       r2.setSelected(true);
       r5.setSelected(false);
    }//GEN-LAST:event_r2MouseClicked

    private void r1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_r1MouseClicked
        // TODO add your handling code here:
        r2.setSelected(false);
        r3.setSelected(false);
        r4.setSelected(false);
        r1.setSelected(true);
        r5.setSelected(false);
    }//GEN-LAST:event_r1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Rating.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Rating.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Rating.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Rating.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Rating(socket,username,qcode).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton r1;
    private javax.swing.JRadioButton r2;
    private javax.swing.JRadioButton r3;
    private javax.swing.JRadioButton r4;
    private javax.swing.JRadioButton r5;
    private javax.swing.JTextField rat;
    private javax.swing.JLabel send;
    // End of variables declaration//GEN-END:variables
}
