/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package QuizPortal;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;
import javax.swing.JOptionPane;

/**
 *
 * @author Manvendra
 */
public class StudentLogin extends javax.swing.JFrame {

    /**
     * Creates new form StudentLogin
     */
    static Socket socket;
    public StudentLogin() {
        initComponents();
        try{
            socket = new Socket("localhost", 5436);
        }catch(IOException e){
            JOptionPane.showMessageDialog(null,"Server Offline");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sname = new javax.swing.JTextField();
        susername = new javax.swing.JTextField();
        slusername = new javax.swing.JTextField();
        spassword = new javax.swing.JTextField();
        sregno = new javax.swing.JTextField();
        slpassword = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ssignup = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        slogin = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        cross = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sname.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(sname, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 350, 50));

        susername.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(susername, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 350, 50));

        slusername.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        slusername.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        slusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                slusernameActionPerformed(evt);
            }
        });
        getContentPane().add(slusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 360, 270, 60));

        spassword.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        spassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spasswordActionPerformed(evt);
            }
        });
        getContentPane().add(spassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 350, 60));

        sregno.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        sregno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sregnoActionPerformed(evt);
            }
        });
        getContentPane().add(sregno, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, 350, 60));

        slpassword.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        slpassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(slpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 446, 270, 60));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("PASSWORD");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, 100, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("USERNAME");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 90, 20));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("NAME");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 70, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("REG. NO.");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 420, 70, -1));

        jLabel2.setText("USERNAME");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 340, 100, -1));

        ssignup.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ssignup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ssignupMouseClicked(evt);
            }
        });
        getContentPane().add(ssignup, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 520, 130, 50));

        jLabel7.setText("PASSWORD");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 420, 100, 30));

        slogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sloginMouseClicked(evt);
            }
        });
        getContentPane().add(slogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 530, 130, 60));
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 10, 40, 30));

        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 0, 40, 40));

        cross.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                crossMouseClicked(evt);
            }
        });
        getContentPane().add(cross, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 10, 30, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QuizPortal/studentlogin.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void spasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_spasswordActionPerformed

    private void sregnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sregnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sregnoActionPerformed

    private void slusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_slusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_slusernameActionPerformed

    private void ssignupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ssignupMouseClicked
        try{
        sendMessage(socket,"signups",susername.getText(),spassword.getText(),sname.getText(),sregno.getText());
        JOptionPane.showMessageDialog(null,"You have been successfully signed up.");
        susername.setText("");
        spassword.setText("");
        sname.setText("");
        sregno.setText("");
    }//GEN-LAST:event_ssignupMouseClicked
catch(IOException e){
               e.printStackTrace();
           }
    }
    private void sloginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sloginMouseClicked
            char[] p = slpassword.getPassword();
            String password1 = new String(p);
            String response;
            ObjectInputStream objectInputStream;
            try{
                sendMessage(socket,"logins", slusername.getText(), password1);
                objectInputStream = new ObjectInputStream(socket.getInputStream());
                response = (String) objectInputStream.readObject();
                if(response.equals("verified"))
                {new SelectStudent(socket,slusername.getText()).setVisible(true);
                dispose();
                }
                else
                JOptionPane.showMessageDialog(null,"Wrong Credentials");
            }catch(IOException|ClassNotFoundException e){
                e.printStackTrace();
            }
            slusername.setText("");
            slpassword.setText("");
    }//GEN-LAST:event_sloginMouseClicked

    private void crossMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crossMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_crossMouseClicked

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        // TODO add your handling code here:
        new HOME().setVisible(true);
        dispose();
    }//GEN-LAST:event_backMouseClicked




public void sendMessage
            (Socket socket, String type, String username,String password,String name,String regno)
            throws IOException {
        ObjectOutputStream objectOutputStream =
                new ObjectOutputStream(socket.getOutputStream());
        //while (true) {
          //  System.out.println("Press 1 to quit");
            //int ch = Integer.parseInt(bufferedReader.readLine());
            //if (ch == 1) {
              //  break;
            //}

            //System.out.println("Enter message");
            //String text = bufferedReader.readLine();
            String[] message={type,name,username,password,regno};
            
            //String from = "Client - " + name;
           // Message message = new Message(text, from, "Server");
          
            objectOutputStream.writeObject(message);
            objectOutputStream.flush();
            }
            public void sendMessage
            (Socket socket, String type, String username,String password)
            throws IOException {
        ObjectOutputStream objectOutputStream =
                new ObjectOutputStream(socket.getOutputStream());
        //while (true) {
          //  System.out.println("Press 1 to quit");
            //int ch = Integer.parseInt(bufferedReader.readLine());
            //if (ch == 1) {
              //  break;
            //}

            //System.out.println("Enter message");
            //String text = bufferedReader.readLine();
            String[] message={type,username,password};
            
            //String from = "Client - " + name;
           // Message message = new Message(text, from, "Server");
          
            objectOutputStream.writeObject(message);
            objectOutputStream.flush();
            }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JLabel cross;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel slogin;
    private javax.swing.JPasswordField slpassword;
    private javax.swing.JTextField slusername;
    private javax.swing.JTextField sname;
    private javax.swing.JTextField spassword;
    private javax.swing.JTextField sregno;
    private javax.swing.JLabel ssignup;
    private javax.swing.JTextField susername;
    // End of variables declaration//GEN-END:variables
}
