/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package QuizPortal;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;
import java.io.Serializable;
import javax.swing.JOptionPane;
import javax.swing.*;
/**
 *
 * @author Manvendra
 */
public class Subject extends javax.swing.JFrame {

    /**
     * Creates new form Subject
     */
    static Socket socket;
    public Subject(Socket socket) {
        initComponents();
        this.socket = socket;
        try{
        ObjectOutputStream objectOutputStream =new ObjectOutputStream(socket.getOutputStream());
        String[] s = {"givesubjects"};
        objectOutputStream.writeObject(s);
        }catch(IOException e){
            e.printStackTrace();
        }
        try{
            ObjectInputStream objectInputStream = new ObjectInputStream(socket.getInputStream());
            String[] str = (String[]) objectInputStream.readObject( );
            selectsub.setModel(new javax.swing.DefaultComboBoxModel(str));
        }catch(IOException|ClassNotFoundException e){
            e.printStackTrace();
        }
    }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        back = new javax.swing.JLabel();
        cross = new javax.swing.JLabel();
        tchoice = new javax.swing.JLabel();
        minimize = new javax.swing.JLabel();
        qcode = new javax.swing.JTextField();
        selectsub = new javax.swing.JComboBox<>();
        addbutton = new javax.swing.JLabel();
        nsubject = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 0, 60, 50));

        cross.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cross.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                crossMouseClicked(evt);
            }
        });
        getContentPane().add(cross, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 10, 30, 30));

        tchoice.setBackground(new java.awt.Color(0, 255, 204));
        tchoice.setText("ENTER");
        tchoice.setOpaque(true);
        tchoice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tchoiceMouseClicked(evt);
            }
        });
        getContentPane().add(tchoice, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 566, -1, 30));

        minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
        });
        getContentPane().add(minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 0, 50, 50));

        qcode.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        qcode.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(qcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 516, 280, 40));

        selectsub.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        selectsub.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "item1", "item2", "item3", "item4" }));
        selectsub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectsubActionPerformed(evt);
            }
        });
        getContentPane().add(selectsub, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 410, 300, 50));

        addbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addbuttonMouseClicked(evt);
            }
        });
        getContentPane().add(addbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 230, 290, 50));

        nsubject.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nsubject.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(nsubject, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 150, 300, 50));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QuizPortal/ADDASUBJECT.jpg"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_minimizeMouseClicked

    private void addbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addbuttonMouseClicked
        // TODO add your handling code here:
        String s[] = {"newsubject",nsubject.getText()};
        try{
        ObjectOutputStream objectOutputStream =new ObjectOutputStream(socket.getOutputStream());
        objectOutputStream.writeObject(s);
        }catch(IOException e){
            e.printStackTrace();
        }
        try{
            ObjectInputStream objectInputStream = new ObjectInputStream(socket.getInputStream());
            String[] str = (String[]) objectInputStream.readObject( );
            if(str[0].equals("duplicate")){
                JOptionPane.showMessageDialog(null,"Subject already present!");
            }
            else
            {
                JOptionPane.showMessageDialog(null,"Subject successfully added");
                selectsub.setModel(new javax.swing.DefaultComboBoxModel(str));
            }
        }catch(IOException|ClassNotFoundException e){
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_addbuttonMouseClicked

    private void crossMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crossMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_crossMouseClicked

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked

        new ADMIN().setVisible(true);
        dispose();
    }//GEN-LAST:event_backMouseClicked

    private void selectsubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectsubActionPerformed
        
    }//GEN-LAST:event_selectsubActionPerformed

    private void tchoiceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tchoiceMouseClicked
       String[] s={"quizcodeselected",selectsub.getSelectedItem().toString(),qcode.getText()};
        try{
        ObjectOutputStream objectOutputStream =new ObjectOutputStream(socket.getOutputStream());
        objectOutputStream.writeObject(s);
        }catch(IOException e){
            e.printStackTrace();
        }
         try{
            ObjectInputStream objectInputStream = new ObjectInputStream(socket.getInputStream());
            String[] str = (String[]) objectInputStream.readObject();
            if(str[0].equals("quizcreated")){
                JOptionPane.showMessageDialog(null, "You Are Ready To Create Quiz - "+qcode.getText());
                new section(socket,selectsub.getSelectedItem().toString(), qcode.getText()).setVisible(true);
                dispose();
            }
         }catch(IOException|ClassNotFoundException e){
             e.printStackTrace();
         }
        
    }//GEN-LAST:event_tchoiceMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Subject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Subject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Subject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Subject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Subject(socket).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addbutton;
    private javax.swing.JLabel back;
    private javax.swing.JLabel cross;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel minimize;
    private javax.swing.JTextField nsubject;
    private javax.swing.JTextField qcode;
    private javax.swing.JComboBox<String> selectsub;
    private javax.swing.JLabel tchoice;
    // End of variables declaration//GEN-END:variables
}
